### ISSUE TITLE
Comment with 3 sequential "#" breaks Lexer

### ISSUE THREAD

**Issue by ricardopieper** [luna/luna#109] opened 2018-01-23 00:24 UTC
Let's say we have the following code:

```
## #comment
«0»def main:
    «1»hello = "Hello, World!"
    None### META {"metas":[{"marker":1,"meta":{"_displayResult":false,"_selectedVisualizer":["base: json","base\\json\\json.html"],"_position":{"fromPosition":{"_vector2_y":0,"_vector2_x":0}}}}]}
```

Now let's try removing the space between ## and #:

![image](https://user-images.githubusercontent.com/4030858/35251526-b2f20a4a-ffc2-11e7-9983-a2d8c26ca07b.png)

```
Uncaught Impossible happened: lexer error: ParseError {errorContexts = [], errorMessage = "string", errorSpan = 3} CallStack (from HasCallStack): error, called at src/Luna/Syntax/Text/Lexer/Runner.hs:23:27 in luna-syntax-text-lexer-0.2-I0yuk6j7XWh8ZJs0AZShKL:Luna.Syntax.Text.Lexer.Runner
C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\text-buffer\lib\text-buffer.js:854
```

Copying and pasting "###" never works too.

Not a deal breaker bug, or maybe not even a bug at all: I just wonder why that happens. Is it following Luna's design?

The same thing happens inside functions too.

**Comment by mikusp** [comment] 2018-01-23 14:44
Closing as a duplicate of luna/luna-studio#212

**Closed by mikusp** 2018-01-23 14:44 UTC
