### ISSUE TITLE
Partial function failure during installation

### ISSUE THREAD

**Issue by Gurkenglas** [luna/luna#77] opened 2018-01-17 13:59 UTC
While installing on Windows 10, I encountered `Prelude.head: empty list`. I suggest that you use call stacks for partial functions or at least `headNote "while extracting the libfoo archive"` or whatever. What I pasted is already the details the "Copy details to clipboard" link gave me.

**Comment by Gurkenglas** [comment] 2018-01-17 14:11
https://github.com/luna/luna/search?utf8=%E2%9C%93&q=head&type= doesn't pop up anything that obviously-to-me looks like part of an installer.

**Comment by wdanilo** [comment] 2018-01-17 21:26
I suspect it is not a `Prelude.head` in our code. Rather it is parsing a json config or something that is assumed to have a field, but the response is empty. I might be wrong here. The team is working on this issue.

**Comment by wdanilo** [comment] 2018-01-17 21:27
Duplicate of https://github.com/luna/luna/issues/76

**Closed by wdanilo** 2018-01-17 21:27 UTC
Labels: bug
