### ISSUE TITLE
Luna studion

### ISSUE THREAD

**Issue by cybervegan** [luna/luna#67] opened 2018-01-17 00:20 UTC
[Enter steps to reproduce:]

1. Download Luna installer
2. Run installer
3. Run .luna/bin/luna-studio/current/luna-studio
4. Message says "Downloading Tutorials" but never completes
5. Expanding window to full screen reveals stack trace as below

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Debian GNU/Linux
**Thrown From**: [luna-studio](...) package 1.0.0

### Stack Trace

Uncaught TypeError: parsed.forEach is not a function

```
At /home/andy/.luna/config/luna-studio/1.0/atom/packages/luna-studio/lib/projects.coffee:160

TypeError: parsed.forEach is not a function
    at Request._callback (/packages/luna-studio/lib/projects.coffee:160:32)
    at Request.self.callback (/packages/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/settings-view/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  3x -0:37.5.0 dev-live-reload:reload-all (atom-workspace.workspace.scrollbars-visible-always)
     -0:12.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-luna-syntax.theme-luna-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
busy-signal 1.4.3 
color-picker 2.2.5 
column-select 0.2.0 
cursor-history 0.11.1 
custom-window-title 1.0.4 
file-icons 2.1.11 
git-blame 1.2.2 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.9.3 
hasklig 0.4.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-gitignore 0.3.0 
language-haskell 1.13.2 
luna-dark-ui 0.1.1 
luna-dpi 0.1.2 
luna-studio 1.0.0 
luna-syntax 0.1.0 
minimap 4.29.6 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
multi-cursor 2.1.5 
sort-lines 0.14.0 
split-diff 1.5.0 
web-view 3.0.0 
```

**Comment by cybervegan** [comment] 2018-01-17 00:24
Fat fingered the issue submission form, sorry. Now corrected and reopened.

**Comment by piotrMocz** [comment] 2018-01-17 00:29
@cybervegan It is a known issue caused by GitHub revoking our access tokens, it is already tracked [here](https://github.com/luna/luna-studio/issues/686). Thank you for reporting, it should be fixed soon :)

**Comment by pmlodawski** [comment] 2018-01-17 10:41
I'm closing it for now as a duplicate of https://github.com/luna/luna-studio/issues/684

The good news is, that we are currently testing fix for this issue, so we are going to resolve this problem in next version.

If you do not want to wait, you can clone the tutorials from https://github.com/luna-packages and Cmd/Ctrl+Shift+O open these projects from Luna Studio.

**Closed by pmlodawski** 2018-01-17 10:41 UTC
