### ISSUE TITLE
Implement HTML Documentation Generator

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#171] opened 2018-03-05 17:51 UTC
Luna Build provides the ability to generate HTML documentation from the source files. 

- [ ] Can parse the generated AST.
- [ ] Handles the new syntax (#144) 
- [ ] Generates HTML documentation.

**Comment by piotrMocz** [comment] 2018-10-08 11:46
This issue is... Done? @wdanilo @lgawlik

**Comment by piotrMocz** [comment] 2018-10-08 11:47
Oh, this is a duplicate of https://github.com/luna/luna/issues/302 -- I created #302 to accomodate the PR, because it wasn't connected anywhere. Please connect your PRs ;)

**Closed by piotrMocz** 2018-10-08 11:47 UTC
Labels: C - Tooling, D - Core Contributor, P - Medium, T - Enhancement
