### ISSUE TITLE
cant rename func name with korean word

### ISSUE THREAD

**Issue by dongugkim** [luna/luna#96] opened 2018-01-19 10:50 UTC
without double quote, it make error

![default](https://user-images.githubusercontent.com/25264202/35147441-f568e72c-fd51-11e7-89d1-d98c95c2c163.PNG)

**Comment by wdanilo** [comment] 2018-01-20 02:19
Could you please try to make a minimal program with it and sent us it's textual representation? It would help us much track this error down. Moreover, it would be easier then to replicate it, because we could copy-paste the text with Korean letters!

**Comment by kimdongug** [comment] 2018-01-20 06:53
def main:
   김동욱 = "Hello, World!"
    nice = 10
    None

**Comment by wdanilo** [comment] 2018-01-21 00:33
@dongugkim thank you for perfect minimal example!

**Comment by jorpic** [comment] 2018-01-21 20:50
@wdanilo, can you please clarify a bit on what behavior is expected.

As I understand, variable names in Luna must begin with lowercase letter or `_`. It is crucial to distinguish variables from constructor names which must begin with uppercase letter.

The problem is that `김` is not lowercase or uppercase. Unicode standard assigns it to the category of "Other Letters": https://codepoints.net/U+ae40

I see a few possible solutions:
 - Use [`isLower`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Char.html#v:isLower) / [`isUpper`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Char.html#v:isUpper). This will allow to use e.g. cyrillic or greek constructor and variable names but still will not allow korean or chinese names.
  - Use [`isUpper`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Char.html#v:isUpper) to distinguish constructor names, but allow any other non uppercase [`isLetter`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Char.html#v:isLetter) in variable names. This will allow `김동욱` and funny symbols like `ᚏᚄ` as valid variable names.

**Comment by wdanilo** [comment] 2018-01-21 21:25
@jorpic Interesting, I didn't know about the `김` character. Using `isLower` / `isUpper` seems like the best solution for now. As I see now, while we were optimizing the Lexer performance, we have limited its support for UTF8 chars. However, it should be easy to fix - the code is here if anyone would like to contribute: https://github.com/luna/luna/blob/master/syntax/text/lexer/src/Luna/Syntax/Text/Lexer/Grammar.hs . 
The needed changes are in function `isIndentBodyChar` and in `symmap` (if the initial char falls out of range  we should try it as var / cons).

**Comment by iamrecursion** [comment] 2018-02-05 14:51
Fixed by #105. Closing.

**Closed by iamrecursion** 2018-02-05 14:51 UTC
Labels: C - Compiler, D - Beginner, S - Help Wanted, T - Bug
