### ISSUE TITLE
Install on windows

### ISSUE THREAD

**Issue by aolko** [luna/luna#74] opened 2018-01-17 10:35 UTC
Can't install on windows 10 x64
`Prelude.head: empty list`
![image](https://user-images.githubusercontent.com/581458/35038236-3cf75952-fb8b-11e7-97fb-fb2f44948084.png)

**Comment by pmlodawski** [comment] 2018-01-17 11:09
Closing this as a duplicate of https://github.com/luna/luna-manager/issues/111

**Closed by pmlodawski** 2018-01-17 11:09 UTC
