### ISSUE TITLE
`.DS_Store` file in luna project causes an error

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#211] opened 2018-06-05 07:35 UTC
```
~/luna/projects/DummyProject/local_libs/.DS_Store/src/:~/luna/projects/DummyProject/local_libs/.DS_Store/src/: getSymbolicLinkStatus: inappropriate type (Not a directory)
```

**Comment by iamrecursion** [comment] 2018-08-21 10:09
Can't currently repro. Waiting for a repro case from @sylwiabr.

**Comment by piotrMocz** [comment] 2018-10-12 12:56
I have been successfully opening projects with `.DS_Store` inside and I cannot reproduce this -- closing.

@sylwiabr if this problem persists, feel free to re-open. If you can provide a repro scenario, that would be awesome.

**Closed by piotrMocz** 2018-10-12 12:56 UTC
Labels: C - Tooling, D - Core Contributor, P - Medium, S - In Progress, T - Bug
