### ISSUE TITLE
Windows executable on the site is not signed

### ISSUE THREAD

**Issue by varosi** [luna/luna#87] opened 2018-01-18 11:50 UTC
This leads to multiple Windows messages for unsafe code on Windows 10.

**Comment by wdanilo** [comment] 2018-01-19 03:14
@kustosz Is this related to what you've been explaining to me? Are we able to fix it or we have to wait until Windows start trusting us?

**Comment by varosi** [comment] 2018-01-19 11:12
Nope, you have to fix it. It needs signing of executables with a certificate for executables signing. It's usually part of deployment process.

**Comment by wdanilo** [comment] 2018-01-20 02:17
@varosi I was speaking with our team today about it. We will handle it soon. If there will be any questions, we will also ask you fro further help with that!

**Comment by piotrMocz** [comment] 2018-10-08 12:29
This is a duplicate of https://github.com/luna/luna-studio/issues/1049 so I suggest the conversation is moved there (that issue has nice pictures, so it's better ;)).

**Closed by piotrMocz** 2018-10-08 12:29 UTC
Labels: C - Tooling, D - Core Contributor, P - High, T - Bug, T - Non-Breaking Change
